version: 0.2

env:
  variables:
      BUILDX_VERSION: "v0.10.0"
      ECR_URL: "701147072243.dkr.ecr.us-east-1.amazonaws.com"
      ECR_REPO_NAME: "geo-tracking-redis"

phases:
  install:
    commands:
      - docker version
      - curl -JLO https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-$BUILDX_VERSION.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URL
  build:
    commands:
      - echo Build started on `date`
      - go mod download
      - CGO_ENABLED=0 go build -ldflags="-s -w"
      - echo Building the Docker image...
      - sed -i 's|alpine|public.ecr.aws/docker/library/alpine|g' Dockerfile
      - docker buildx create --use --name crossx
      - docker buildx build --push --platform=linux/arm64 -t $ECR_URL/$ECR_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .

artifacts:
  files:
    - '**/*'