version: 0.2

env:
  variables:
      BUILDX_VERSION: "v0.10.0"
      
phases:
  install:
    commands:
      - aws --version
      - kubectl version --client
  pre_build:
    commands:
      - aws sts get-caller-identity
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name cb-test-cluster
  build:
    commands:
      - IMAGE_TAG=$(cat image.txt)
      - kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE_TAG
  post_build:
    commands:
      - kubectl get pods